[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"

dependencies =[
    "bpy==3.6.0",
    "cython==3.2.1",
    "glumpy>=1.2.1",
    "h5py==3.15.1",
    "huggingface-hub[hf-transfer]==0.36.0",
    "imageio==2.37.2",
    "imgaug>=0.4.0",
    "kiwisolver==1.4.9",
    "mathutils<5.0.0",
    "matplotlib==3.10.7",
    "ninja==1.11.1.1",
    "numpy==1.26.4",
    "open3d==0.19.0",
    "opencv-contrib-python==4.9.0.80",
    "opencv-python==4.9.0.80",
    "pillow==11.3.0",
    "pybind11==2.12.0",
    "pyopengl>=3.1.0",
    "pypng>=0.20220715.0",
    "pyrender>=0.1.45",
    "pytz>=2026.2",
    "rich==14.2.0",
    "scipy==1.15.3",
    "setuptools<70.0.0",
    "tensorboard>=2.20.0",
    "tqdm>=4.66.5",
    "transformations==2024.6.1",
    "triangle>=20250106",
    "trimesh==4.2.2",
    "ultralytics==8.4.16",
    "vispy>=0.16.1",
    "wheel",
    "pyvirtualdisplay",
	"comm==0.2.3",
	"pip",
	"onnxruntime-openvino==1.23.0",
	"onnx",
]

# 这里定义安装模式
[project.optional-dependencies]
cpu =[
    "torch>=2.1.2",
    "torchaudio>=2.1.2",
    "torchvision>=0.16.2",
    "kornia==0.6.9",
    "diffrp-nvdiffrast>=0.3.3.1",
    "fvcore==0.1.5.post20221221",
]
cuda =[
    "torch>=2.1.2",
    "torchaudio>=2.1.2",
    "torchvision>=0.16.2",
    "kornia==0.6.9",
    "diffrp-nvdiffrast>=0.3.3.1",
    "fvcore==0.1.5.post20221221",
]

[dependency-groups]
train =[
    "bpy==3.6.0",
    "kasal-6d==0.1.3",
    "polyscope<2.4.0",
    "pymeshlab>=2023.12.post1",
]

[tool.uv]
compile-bytecode = true
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'"
]
# 这里是核心：防止 CPU 和 CUDA 同时安装
conflicts = [[ { extra = "cpu" }, { extra = "cuda" } ]]

[tool.uv.extra-build-dependencies]
glumpy =["setuptools", "numpy", "cython", "wheel"]

# 定义索引
[[tool.uv.index]]
name = "blender"
url = "https://download.blender.org/pypi/"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

# 条件化源映射
[tool.uv.sources]
bpy = { index = "blender" }
torch =[
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cuda", extra = "cuda" }
]
torchvision =[
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cuda", extra = "cuda" }
]
torchaudio =[
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cuda", extra = "cuda" }
]